apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: swiggy-container
        image: manoharmattepu/swiggy:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Replace with the port your app runs on

