apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  labels:
    app: swiggy
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000  # Replace with the port your app runs on
  selector:
    app: swiggy
